## Numpy and Pandas

In [1]:
import numpy as np
import pandas as pd
import statistics as stats

In [14]:
a = [[10,20,30],[40,50,60]]
arr = np.array(a)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.astype(str))
print(arr.dtype)
print(arr.ndim)


[[10 20 30]
 [40 50 60]]
(2, 3)
6
int64
[['10' '20' '30']
 ['40' '50' '60']]
int64
2


In [22]:
arr1 = [10,20,30,40,50,60]
arr2 = [30,40,50,10,40,20]
c = np.divide(arr1,arr2)
print(c)

[0.33333333 0.5        0.6        4.         1.25       3.        ]


In [24]:
arr1 = [2,4,6,8,2,6,8]
arr2 = [3]
c = np.power(arr1,arr2)
print(c)

[  8  64 216 512   8 216 512]


In [29]:
arr1 =[20,30,40,49,64,81,101,202]
print(np.sqrt(arr1))


[ 4.47213595  5.47722558  6.32455532  7.          8.          9.
 10.04987562 14.2126704 ]


In [45]:
import numpy as np
a = np.array([[10,20],[30,40]])
b = np.array([[2,4],[3,6]])
print(np.concatenate([a,b]))


[[10 20]
 [30 40]
 [ 2  4]
 [ 3  6]]


In [46]:
print(np.hstack([a,b]))

[[10 20  2  4]
 [30 40  3  6]]


In [47]:
print(np.vstack([a,b]))

[[10 20]
 [30 40]
 [ 2  4]
 [ 3  6]]


In [65]:
a = np.array([10,20,30,40,50,60,70,80,90])
b = (np.array_split(a,3))
print(b)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]


In [62]:
c = np.delete(b,[2])
print(c)

[10 20 50 60 70 80 90]


In [66]:
a = np.array([[10,20],[30,40]])
print(np.append(a,[90,100]))

[ 10  20  30  40  90 100]


In [81]:
a = np.array([3,5,3,1,8,4,9,6])
s = a > 4
new = a[s]
print(new)

[5 8 9 6]


In [89]:
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.median(a))

39
1
9
4.875
[ 3  8 11 12 20 24 33 39]
4.5


In [108]:
a = [100,200,300,400,500]
b = [10,20,23,34,45]
price = np.array(a)
quantity = np.array(b)
print(price,quantity)
c = np.cumprod([price, quantity], axis = 0)
print(c)
print(np.sum(c))

[100 200 300 400 500] [10 20 23 34 45]
[[  100   200   300   400   500]
 [ 1000  4000  6900 13600 22500]]
49500


In [122]:
baked_food = [20,130,100,130,150,108,70,180,90]
a = np.array(baked_food)
print(np.mean(a))
print(np.median(a))
print(stats.mode(a))
print(np.std(a))
print(np.var(a))

108.66666666666667
108.0
130
44.080734012844104
1943.111111111111


In [126]:
price = [300,200,400,500,500]
sales = [10,20,40,50,20]
print(np.corrcoef([price,sales]))

[[1.         0.56011203]
 [0.56011203 1.        ]]


In [2]:
data = {"Name": ["Haroon","Mamoon","Awais"],
       "Age": [23, 17, 22],
       "Salary": [300000,250000,400000]}
df = pd.DataFrame(data)
print(df)

     Name  Age  Salary
0  Haroon   23  300000
1  Mamoon   17  250000
2   Awais   22  400000


In [17]:
data = pd.read_excel("Word_Meaning.xlsx")
print(data)

    Meaning    Unnamed: 1
0  precious         قیمتی
1    wisely   سمجھداری سے
2   forever  ہمیشہ کے لیے
3  treasure         خزانہ


In [20]:
data = pd.read_csv("personal_information_data.csv")
print(data.head(10))
print(data.tail(10))
print(data.info())

   ID First Name   Last Name  Age  Gender                               Email  \
0   1     Marcia     Preston   24  Female              guzmanjoshua@yahoo.com   
1   2      Sarah       Owens   64  Female       vaughnjacqueline@chandler.com   
2   3     Sydney      Hinton   56  Female  nicholasbradley@butler-hopkins.org   
3   4    Richard    Morrison   68   Other               gregory68@hotmail.com   
4   5    Stephen   Rodriguez   50   Other               oharrison@hotmail.com   
5   6       Joel  Hutchinson   19  Female                  bmahoney@yahoo.com   
6   7      Scott      Fisher   33   Other                   ehill@hotmail.com   
7   8       Jose     Johnson   46    Male               michael74@barrett.com   
8   9      Maria    Campbell   38  Female             josephcamacho@yahoo.com   
9  10      Derek   Gillespie   19  Female           patrickwillis@hotmail.com   

            Phone Number                                            Address  
0             8691033648      

In [3]:
data = pd.read_excel("practice_data.xlsx")
# print(data)
data["Salary"] = data["Salary"].replace(np.nan, 81543)
data["Gender"] = data["Gender"].fillna(method = "ffill")
print(data)

       Name  Age  Gender    Salary   Department            Joining Date  \
0      John   22  Female  111857.0        Sales 2021-04-21 17:00:53.856   
1      Jane   25    Male   82489.0        Sales 2021-05-28 17:00:53.856   
2   Michael   25  Female  114665.0        Sales 2019-12-28 17:00:53.856   
3     Emily   31    Male   71504.0    Marketing 2021-03-05 17:00:53.856   
4     Laura   41    Male   79866.0    Marketing 2021-12-27 17:00:53.856   
5     David   43  Female  114212.0  Engineering 2022-06-08 17:00:53.856   
6     Chris   58    Male   41723.0    Marketing 2022-08-19 17:00:53.856   
7     Sarah   45    Male   73890.0           HR 2022-02-10 17:00:53.856   
8    Daniel   28  Female   47591.0    Marketing 2023-07-31 17:00:53.856   
9   Jessica   46    Male   88146.0      Finance 2023-01-25 17:00:53.856   
10     Paul   46    Male   89300.0        Sales 2020-12-17 17:00:53.856   
11    Megan   34  Female   81543.0  Engineering 2020-03-16 17:00:53.856   
12      Tom   23    Male 

C:\Users\Z\AppData\Local\Temp\ipykernel_7336\3159140384.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["Gender"] = data["Gender"].fillna(method = "ffill")


In [15]:
data.loc[(data["Age"] >= 30), "UnderAge"] = "Under Age"
data.loc[(data["Age"] < 30), "UnderAge"] = "Not Under Age"
print(data)

       Name  Age  Gender    Salary   Department            Joining Date  \
0      John   22  Female  111857.0        Sales 2021-04-21 17:00:53.856   
1      Jane   25    Male   82489.0        Sales 2021-05-28 17:00:53.856   
2   Michael   25  Female  114665.0        Sales 2019-12-28 17:00:53.856   
3     Emily   31    Male   71504.0    Marketing 2021-03-05 17:00:53.856   
4     Laura   41    Male   79866.0    Marketing 2021-12-27 17:00:53.856   
5     David   43  Female  114212.0  Engineering 2022-06-08 17:00:53.856   
6     Chris   58    Male   41723.0    Marketing 2022-08-19 17:00:53.856   
7     Sarah   45    Male   73890.0           HR 2022-02-10 17:00:53.856   
8    Daniel   28  Female   47591.0    Marketing 2023-07-31 17:00:53.856   
9   Jessica   46    Male   88146.0      Finance 2023-01-25 17:00:53.856   
10     Paul   46    Male   89300.0        Sales 2020-12-17 17:00:53.856   
11    Megan   34  Female   81543.0  Engineering 2020-03-16 17:00:53.856   
12      Tom   23    Male 

In [12]:
data["Full Name"] = data["Name"].str.capitalize() + " " + data["Gender"]
print(data)

       Name  Age  Gender    Salary   Department            Joining Date  \
0      John   22  Female  111857.0        Sales 2021-04-21 17:00:53.856   
1      Jane   25    Male   82489.0        Sales 2021-05-28 17:00:53.856   
2   Michael   25  Female  114665.0        Sales 2019-12-28 17:00:53.856   
3     Emily   31    Male   71504.0    Marketing 2021-03-05 17:00:53.856   
4     Laura   41    Male   79866.0    Marketing 2021-12-27 17:00:53.856   
5     David   43  Female  114212.0  Engineering 2022-06-08 17:00:53.856   
6     Chris   58    Male   41723.0    Marketing 2022-08-19 17:00:53.856   
7     Sarah   45    Male   73890.0           HR 2022-02-10 17:00:53.856   
8    Daniel   28  Female   47591.0    Marketing 2023-07-31 17:00:53.856   
9   Jessica   46    Male   88146.0      Finance 2023-01-25 17:00:53.856   
10     Paul   46    Male   89300.0        Sales 2020-12-17 17:00:53.856   
11    Megan   34  Female   81543.0  Engineering 2020-03-16 17:00:53.856   
12      Tom   23    Male 

In [32]:
data["Bouns"] = data["Salary"]/100*20
gb = data.groupby(["Department", "Gender"]).agg({"Salary":"max"})
print(gb)

                      Salary
Department  Gender          
Engineering Female  114212.0
Finance     Female   91713.0
            Male    116904.0
HR          Male     73890.0
Marketing   Female   76522.0
            Male     81543.0
Sales       Female  114665.0
            Male     89300.0


In [20]:
df = {"Months": ["january","February","March","April"]}
a = pd.DataFrame(df)

def extract(value):
    return value[0:3]

a["short_months"] = a["Months"].map(extract)
print(a)

     Months short_months
0   january          jan
1  February          Feb
2     March          Mar
3     April          Apr


In [41]:
data1 = {"EID": ["E01", "E02", "E08", "E04", "E09", "E06","E07"],
        "Name": ["Haroon", "Asad", "Abdullah", "Mamoon","Muneeb","Hussnain","Awais"],
        "Age": [23,26,32,54,34,47,34]}
data2 = {"EID": ["E01", "E02", "E03", "E04", "E05", "E06","E07"],
        "Salary": [45000,36000,28000,40000,39000,42000,50000]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
print(df1)
print(df2)

   EID      Name  Age
0  E01    Haroon   23
1  E02      Asad   26
2  E08  Abdullah   32
3  E04    Mamoon   54
4  E09    Muneeb   34
5  E06  Hussnain   47
6  E07     Awais   34
   EID  Salary
0  E01   45000
1  E02   36000
2  E03   28000
3  E04   40000
4  E05   39000
5  E06   42000
6  E07   50000


In [49]:
print(pd.merge(df1,df2, on = "EID", how = "right"))

   EID      Name   Age  Salary
0  E01    Haroon  23.0   45000
1  E02      Asad  26.0   36000
2  E03       NaN   NaN   28000
3  E04    Mamoon  54.0   40000
4  E05       NaN   NaN   39000
5  E06  Hussnain  47.0   42000
6  E07     Awais  34.0   50000


In [6]:
data1 = {"EID": ["E01", "E02", "E08", "E04", "E09", "E06","E07"],
        "Name": ["Haroon", "Asad", "Abdullah", "Mamoon","Muneeb","Hussnain","Awais"],
        "Age": [23,26,32,54,34,47,34]}
data2 = {"EID": ["E08", "E09", "E10", "E11", "E12", "E13","E14"],
        "Name": ["Mubeen", "Ahmad", "Mursad", "Hanzla","Farid","Farhan","Umar"],
        "Age": [33,46,42,34,44,37,23]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
print(df1)
print(df2)

   EID      Name  Age
0  E01    Haroon   23
1  E02      Asad   26
2  E08  Abdullah   32
3  E04    Mamoon   54
4  E09    Muneeb   34
5  E06  Hussnain   47
6  E07     Awais   34
   EID    Name  Age
0  E08  Mubeen   33
1  E09   Ahmad   46
2  E10  Mursad   42
3  E11  Hanzla   34
4  E12   Farid   44
5  E13  Farhan   37
6  E14    Umar   23


In [53]:
print(pd.concat([df1,df2]))

   EID      Name  Age
0  E01    Haroon   23
1  E02      Asad   26
2  E08  Abdullah   32
3  E04    Mamoon   54
4  E09    Muneeb   34
5  E06  Hussnain   47
6  E07     Awais   34
0  E08    Mubeen   33
1  E09     Ahmad   46
2  E10    Mursad   42
3  E11    Hanzla   34
4  E12     Farid   44
5  E13    Farhan   37
6  E14      Umar   23


In [66]:
data1 = {"fruits": ["Mango", "Apple", "Banana", "Papaya"],
        "prices": [200, 250, 100, 150],
        "quantity": [50, 20, 30, 15]}
df1 = pd.DataFrame(data1)
print(df1)
df2 = df1.copy()
df2.loc[0, "prices"] = 150
df2.loc[1, "prices"] = 200
df2.loc[2, "prices"] = 120
df2.loc[3, "prices"] = 100
df2.loc[0, "quantity"] = 40
df2.loc[1, "quantity"] = 20
df2.loc[2, "quantity"] = 50
df2.loc[3, "quantity"] = 20
print(df2)

   fruits  prices  quantity
0   Mango     200        50
1   Apple     250        20
2  Banana     100        30
3  Papaya     150        15
   fruits  prices  quantity
0   Mango     150        40
1   Apple     200        20
2  Banana     120        50
3  Papaya     100        20


In [70]:
com = df1.compare(df2, keep_shape = True)
print(com)

  fruits       prices       quantity      
    self other   self other     self other
0    NaN   NaN    200   150     50.0  40.0
1    NaN   NaN    250   200      NaN   NaN
2    NaN   NaN    100   120     30.0  50.0
3    NaN   NaN    150   100     15.0  20.0


In [2]:
dic = {"keys": ["k1", "k2", "k1", "k2"],
      "Names": ["Haroon", "Sajjad", "Ali", "Amjad"],
      "Houses": ["Green", "Red", "Blue", "Black"],
      "Grades": ["3rd","8th", "9th", "5th"]}
df = pd.DataFrame(dic)
print(df)
print(df.pivot(index="keys",columns="Names",values=["Houses","Grades"]))
print(pd.melt(df, id_vars=["Names"],value_vars=["Houses","Grades"],var_name="Houses&Grades",value_name="values"))

  keys   Names Houses Grades
0   k1  Haroon  Green    3rd
1   k2  Sajjad    Red    8th
2   k1     Ali   Blue    9th
3   k2   Amjad  Black    5th
      Houses                      Grades                    
Names    Ali  Amjad Haroon Sajjad    Ali Amjad Haroon Sajjad
keys                                                        
k1      Blue    NaN  Green    NaN    9th   NaN    3rd    NaN
k2       NaN  Black    NaN    Red    NaN   5th    NaN    8th
    Names Houses&Grades values
0  Haroon        Houses  Green
1  Sajjad        Houses    Red
2     Ali        Houses   Blue
3   Amjad        Houses  Black
4  Haroon        Grades    3rd
5  Sajjad        Grades    8th
6     Ali        Grades    9th
7   Amjad        Grades    5th
